### ISSUE TITLE
Could you also fix Sandbox 2.exe (aka "Crysis Editor") for Crysis 1 / Crysis Wars ?

### ISSUE THREAD

**Issue by ChrisHeller1991** [ccomrade/c1-launcher#33] opened 2023-11-12 18:06 UTC
Hello everyone involved in the development of this wonderful project!
Thank you so much for all the work you put into this!

Your files work perfectly fine on my new PC which runs with a Ryzen 9 7950X3D. Crysis Wars now starts without problem (Win10-64bit, Steam-Version).

_**But i'd like to ask if you could also fix the Editors for Crysis 1 and Crysis Wars.**_

They run on my old Win10 64-bit machine which has an Intel Core i9-9900K but they crash to desktop after loading the GUI (32-bit Editor) or they won't even start (64-bit Editor) on my new PC.

It would be so nice to be able to use them along with modern hardware 😄 

# Crysis 1

The only Crysis 1 version i own is the DVD version. The editor could be installed from one of the DVDs.
I do not know if the Steam/GOG/Origin versions come with the editor.

#### 32 Bit Editor
When starting the 32-bit Editor i can see the splash screen and it loads up the entire Editor Window.
After about half a second it crashes without further information.

Splashscreen and editor load
![Crysis1_Editor_32Bit_StartUp](https://github.com/ccomrade/c1-launcher/assets/59688992/21031612-e0fd-469a-95b3-dbf94348c24e)

Editor window right before it crashes
![Crysis1_Editor_32Bit_Final](https://github.com/ccomrade/c1-launcher/assets/59688992/ff5e1681-8768-48b9-bed9-b09833a912db)

This is the Editor log file: _*edit: Moved log to file_
[EditorLog.txt](https://github.com/ccomrade/c1-launcher/files/13357977/EditorLog.txt)

#### 64 Bit Editor

It immediately shows me the following error message:

```
D:\_Games\Crysis\Crysis1\Bin64\Editor.exe

The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

![Crysis1_Editor_64Bit_EN](https://github.com/ccomrade/c1-launcher/assets/59688992/5fe5b0fa-dc68-4a85-a4c1-2c112d52205d)

# Crysis Wars

I own the DVD version and the Steam version of Crysis Wars.
The Steam Version does not come with the Editor. ~~As far as i remember one could install the editor from the DVD.~~
_(Edit: I just checked the DVD. There is no Sandbox Editor for Crysis Wars. I guess i must have downloaded it years ago...)_
I do not know whether the other platforms also ship with the editor.

The Editor behavior is exactly the same as in Crysis 1 above:
The 32 bit version loads the editor window and crashes shortly after.
The 64 bit version shows the same error as the Crysis 1 64 bit editor.

---

Thank you for your time and effort ❤️

**Comment by ccomrade** [comment] 2023-11-13 22:02
Hello, i plan to add support for Editor and also Crysis Warhead. The problem with these two is that their executables are not just launchers. They contain a lot of additional stuff. Crysis Warhead has both CryGame and CryAction integrated into its executable. Editor has a complete, well, editor inside its executable. That means the original executable cannot be simply replaced. The launcher has to somehow cooperate with original executables, which is tricky, but doable.

By the way, that 64-bit Editor error looks interesting. Do you think you can try to obtain some details about it? The error message suggests checking event log or even some [sxstrace.exe](https://ss64.com/nt/sxstrace.html). I guess the problem is somehow related to MFC80.DLL, which Editor needs.

In any case, thanks for the info.

**Comment by ChrisHeller1991** [comment] 2023-11-14 22:31
>Hello, i plan to add support for Editor and also Crysis Warhead. 

It makes me very happy to hear that you are working on it!

>Do you think you can try to obtain some details about it?

Sure. I used sxstrace.exe and got this:

[Crysis1Editor_Trace.txt](https://github.com/ccomrade/c1-launcher/files/13357642/Crysis1Editor.txt)

Long story short: I was simply missing the Visual C++ Redistributable on my new PC.
I installed it and now the splash screen also appears when starting the 64-bit Editor (Crysis1 & Crysis Wars).

It now fails (while the editor splash screen is shown) to initialize the Renderer.

These are the Errors in the Event Viewer:

32-bit Editor
```
Faulting application name: Editor.exe, version: 1.1.1.5767, time stamp: 0x471f96b2
Faulting module name: CryRenderD3D10.dll, version: 1.1.1.6156, time stamp: 0x47d6d2e4
Exception code: 0xc000001d
Fault offset: 0x00024ae3
Faulting process id: 0x7a40
Faulting application start time: 0x01da174556f24c72
Faulting application path: D:\_Games\Crysis\Crysis1\Bin32\Editor.exe
Faulting module path: D:\_Games\Crysis\Crysis1\Bin32\CryRenderD3D10.dll
Report Id: 92e4ea9e-d5fb-43ea-a80f-943992965e43
Faulting package full name: 
Faulting package-relative application ID: 
```
and also this
```
Windows cannot access the file "" for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program CryENGINE 2 ® Sandbox 2 ™ because of this error.

Program: CryENGINE 2 ® Sandbox 2 ™
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0
```
Editor loading behavior is same as in the initial post. It loads the editor, i can see the window and as soon as i move my mouse it crashes.

---

64-bit Editor
```
Faulting application name: Editor.exe, version: 1.1.1.5767, time stamp: 0x471f990a
Faulting module name: CryRenderD3D10.dll, version: 1.1.1.6156, time stamp: 0x47d6dbaa
Exception code: 0xc0000005
Fault offset: 0x00000000000c7442
Faulting process id: 0x9194
Faulting application start time: 0x01da1745523df933
Faulting application path: D:\_Games\Crysis\Crysis1\Bin64\Editor.exe
Faulting module path: D:\_Games\Crysis\Crysis1\Bin64\CryRenderD3D10.dll
Report Id: 1eeea4fe-e148-4cc7-aae6-771c9eef6cbd
Faulting package full name: 
Faulting package-relative application ID: 
```
Editor loading behavior: The splash screen shows up and loads for a short amount of time. As soon as it says "Initializing Renderer..." it crashes. The editor window is not shown.

I hope this helps you somehow.

**Comment by NitroArms** [comment] 2024-01-08 01:37
The Editor work fine for me till I updated GPU driver to 546.33. Now it's broken. Launcher worked for the game. Thank You!!
 This is what I got from Windows 11 EV:
Faulting application name: Editor.exe, version: 1.1.1.5767, time stamp: 0x471f990a
Faulting module name: CryRenderD3D10.dll, version: 1.1.1.6156, time stamp: 0x47d6dbaa
Exception code: 0xc0000005
Fault offset: 0x00000000000c7442
Faulting process id: 0x0x10E4
Faulting application start time: 0x0x1DA41C8570CA809
Faulting application path: C:\GOG Games\Crysis\Bin64\Editor.exe
Faulting module path: C:\GOG Games\Crysis\Bin64\CryRenderD3D10.dll
Report Id: 63e4ca40-79ee-481d-9d9e-f4bbddcbf6f6
Faulting package full name: 
Faulting package-relative application ID: 
 I have a lot of time in some of my maps, I thank every one working on this.

**Comment by ccomrade** [comment] 2024-01-08 18:33
Only 64-bit version should be affected by this nVidia driver bug. 32-bit one should still work fine, but who knows. I'm currently working on Editor support together with few other things. It will be in the next release.

**Comment by NitroArms** [comment] 2024-01-10 01:57
I found that if "-devmode" is in the cmd line of the short cut, the game will load the stock(default island) map. No matter what you export to engine from editor. Remove devmode cmd shortcut, it will load the map that was exported to the engine. Am I missing something? When I put -dx9 in the cmd line of Crysis shortcut I get black screen, will not lunch game. I am on windows 11 gtx 3090. Hope this helps, once more thank you.

**Comment by ccomrade** [comment] 2024-02-03 19:54
@ChrisHeller1991
@NitroArms

Editor support is implemented. Could you test if it fixes the issues for you? Here are the EXEs. Or you can take those big ones from CI/CD artifacts. The original Editor.exe is also needed.

[c1-launcher-v5-build-editor.zip](https://github.com/ccomrade/c1-launcher/files/14152717/c1-launcher-v5-build-editor.zip)

**Comment by Pureshechka** [comment] 2024-02-04 07:43
The files from the archive above solved the problem for me.
Previously, Editor 64 crashed on startup.
Good job!

**Comment by ccomrade** [comment] 2024-02-07 19:28
No problem. I'm glad that it works. Thank you all for reporting the issue and verifying the fix.

**Closed** 2024-02-07 19:28 UTC

**Comment by ccomrade** [comment] 2025-01-26 19:38
@Archviz360 check Editor.log

**Comment by Archviz360** [comment] 2025-01-26 19:44
where is Editor.log

**Comment by ccomrade** [comment] 2025-01-26 20:13
In Crysis folder if it's writable. If not, then logs are in `Documents/My Games/Crysis`. I think Editor doesn't work properly without writable Crysis folder. That could be the issue. Crysis folder isn't writable when it's inside Program Files.

**Comment by Archviz360** [comment] 2025-01-26 22:02
the editor shows loading screen then it just diaspears. i couldnt find the log file in Documents/My Games/Crysis

**Comment by ccomrade** [comment] 2025-01-27 22:34
And in Crysis folder?

**Comment by Archviz360** [comment] 2025-01-27 22:44
coudlnt find any editor.log

**Comment by Archviz360** [comment] 2025-01-29 02:02
game works

**Comment by ThisWrongGuy** [comment] 2025-11-15 17:26
Hello guys ! I have the same issue , the sandbox just showing the opening screen , saying that it loads everything and suddenly just shut down no error message , i using Win 11 Pro version 25H2 . I tried all the launchers what attached , but nothing changes , i buyed the gog version yesterday . I really appreciate the time and effort you put in it , you brought back a lot of happy childhood memories , thank you sir !  :)

**Comment by crybog76** [comment] 2026-01-26 13:49
Hello to everybody!
i reference my post to attached images in ChrisHeller1991on Feb 7, 2024 post;
the two images show editor in 32 bit and 64bit mode;
they works, fine, but the editor in 32bit mode has a trouble because the dimension of the viewport are wrong (0x1171) and the status bar where are shown selection, lock selection, x,y,z, coordinates of selection and others is non well shown,
somebody has any idea why?
My installation is affected by this trouble too.
Thanks

**Comment by ccomrade** [comment] 2026-01-26 20:49
Hello, it should be fixed in both 32-bit and 64-bit. Are you running the editor using c1-launcher v8 (`EditorLauncher.exe`)?

**Comment by crybog76** [comment] 2026-01-28 12:51
Hello,

thank you for your answer

unfortunately i'm not able to run editorlaucher.exe on my system;

i'm looking for a tournaround with regedit or manifets files

chatgpt suggest some solution but doesn't work

if you got some idea i'm very glad

Thank you

**Comment by ccomrade** [comment] 2026-01-28 21:05
> unfortunately i'm not able to run editorlaucher.exe on my system;

It doesn't work? Please send `Editor.log` after running `EditorLauncher.exe`.

**Comment by crybog76** [comment] 2026-01-29 10:08
antivirus lock the .exe; antivirus is managed by domain administrator directly

**Comment by ccomrade** [comment] 2026-01-31 11:12
Ah this endless battle with antiviruses... Did you try both C1-Launcher v7 and v8? My code signing certificate expired a few months ago, so i had to renew it. The new certificate was used to sign v8, while v7 is signed using the old one. The new one may not have enough reputation yet.

By the way, on virustotal.com, editor launchers from both v7 ([32-bit](https://www.virustotal.com/gui/file/1b7f3e557e693a6c61f57d0e4547a99365c13088430f9483e85d376dcfcdeb30), [64-bit](https://www.virustotal.com/gui/file/f0ba8da332761730b1644f0188bf989a3496f4a8e0bbd3dc3e69a15e2be728fb)) and v8 ([32-bit](https://www.virustotal.com/gui/file/f53bc1b37c4124015dd57f805b1e8b17931fc4a58187df74d3d62c1ece80015c), [64-bit](https://www.virustotal.com/gui/file/746ac7fea9813f2121d8fafb55fead140cf1b77f52810be612871f4161aaf93d)) are 100% clean.

**Comment by crybog76** [comment] 2026-02-04 14:16
Ok, thank you very much, i not remember your .exe version, i'll try as soon as i can, i'll keep you updated
